# Statistical Computation

```{r echo=FALSE, message=FALSE}
# Global options
options(
  tibble.pillar.subtle = FALSE, 
  tibble.pillar.sigfig = 7, 
  tibble.pillar.min_title_chars = 10,
  scipen = 5
  )

library(knitr)

# Chunk options
opts_chunk$set(
  # General
  comment = NA,
  message = FALSE, 
  warning = FALSE,
  tidy = FALSE,
  
  # Figures
  fig.align = 'center',
  fig.height = 6,
  fig.width = 6,  
  out.width = '50%' 
  
  
  )
```


The first set of tools we will discuss will be related to statistical computation. Although there are many computational tools for statistical analysis, the first tools we will add to your computational toolkit is R. R is a free software environment for statistical computing and graphics. It can be installed on a variety of operating systems, including the MacOS, Windows, and UNIX platforms. To really make use of the computational power of R, we are also going to introduce you to RStudio, an open-source front-end^[Specifically, RStudio is branded as an "integrated development environment (IDE) [that] includes a console, syntax-highlighting editor that supports direct code execution, as well as tools for plotting, history, debugging and workspace management."] to R.


The initial chapters of this document will address:

- Installing R and RStudio;
- Getting started with R's computational syntax;
- Wrangling data using functions from the **dplyr** package; and
- Visualizing data using functions from the **ggplot2** package.


<br /><br />